### ISSUE TITLE
Discuss TreeLDR: Tree Linked Data Representation

### ISSUE THREAD

**Issue by wyc** [spruceid/didkit#152]
**Problem**: it's hard for developers to work with JSONSchema and JSON-LD contexts.

**Solution**: Introduce new record syntax called TreeLDR (Tree Linked Data Representation) that can succinctly express JSON-LD contexts, CBOR-LD contexts, RDFa contexts, JSONSchema, and other reprs on schema.org. 300 lines of hard-to-manipulate JSON becomes 50 lines of familiar struct definitions as you would encounter in Rust, C++, etc.

The challenge is that between LD contexts and JSONSchema there is a strange relationship that's not as simple as "LD contexts are a strict superset of JSONSchema". Therefore, TreeLDR will in some cases be one-way compilation to the schema representation of choice, and if you go the other way, it may produce a proper subset of the original TreeLDR.

We can imagine this DSL (Is it technically a DSL? I guess all grammars make _languages_, even if not turing-complete programming ones?) to further generate libraries across languages and platforms. Maybe you can use this to create a Python SDK that uses DIDKit under the hood, dealing with your specific credential types.

Similar efforts in other places to draw inspiration:
- JHipster's [JDL](https://www.jhipster.tech/jdl/)
- [Protobuf](https://developers.google.com/protocol-buffers) and other wire protocol specifications
- [CDDL](https://tools.ietf.org/html/rfc8610)

Example of what it could look like:
```
use schema_org::URL;
use custom::OtherRecord;

BasicProfile :: Record {
    name :: String required
    description :: String required
    logo :: URL required schemes("http"|"https")
    website :: URL required schemes("http"|"https")
}

AdvancedProfile :: {BasicProfile, OtherRecord} {
    age :: Number required min(0) max(99)
}

type Profile = BasicProfile | AdvancedProfile
```

Open questions/observations:
- How much type system do we want? I think ADTs are a good thing to have here, like sum types in Haskell. Product types should be naturally expressed as records instead of lists to avoid that Haskell pothole. Maybe Rust is a better source of inspiration here. What about traits/type classes?
- We fortunately have a wonderful testbed for this: anything on schema.org should have a sane representation if it is straightforward there--and we should make the hard things easier.

**Comment by wyc** [comment]
Also relevant: https://awslabs.github.io/smithy/

**Comment by oed** [comment]
Seems like there might be some overlap with this and IPLD schemas: https://ipld.io/docs/schemas/intro/

**Comment by timothee-haudebourg** [comment]
If I understand right, the goal is to design a strongly typed schema definition language that would compile (or transpile) into various less user-friendly languages (LD context, JSONSchema, etc.). What stands out to me in the above example as a unique feature, that is not present with other mentioned user-friendly schema definition languages, are the refinement types. 

I'm less sure to fully grasp the "create a Python SDK that uses DIDKit under the hood" part. Correct me if I'm wrong, but that would mean:
 - Transpiling the TreeLDR schema definition into the target programming language (Python here) type definitions.
 - Generating some code in the target PL that uses those type definitions in combination with DIDKit. Even reading the DIDKit examples I don't have a precise idea of common usage patterns, so that's the part that remains a bit blurry for me. A concrete example of the complete flow from TreeLDR to the generated code could help here.

**Comment by sbihel** [comment]
TreeLDR now has its own repo: [spruceid/treeldr](https://github.com/spruceid/treeldr).
